# Generated by Django 6.0.6 on 2026-06-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_smart_list_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bg_color',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='project',
            name='bg_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
