# Generated by Django 6.0.6 on 2026-10-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_section_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='objective',
            field=models.CharField(blank=True, choices=[('active', 'Objectif actif'), ('fridge', 'Au frigo')], default='', max_length=8),
        ),
    ]
