# Generated by Django 6.0.6 on 2026-07-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitreminder',
            name='last_sent_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
