# Generated by Django 6.0.6 on 2026-10-07 21:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('focus', '0002_focussession_planned_seconds'),
        ('projects', '0005_project_objective'),
        ('tasks', '0010_task_blocker_task_postpone_count_task_proposed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('jokers_per_month', models.PositiveSmallIntegerField(default=2)),
                ('today_limit', models.PositiveSmallIntegerField(default=3)),
                ('review_weekday', models.PositiveSmallIntegerField(default=6)),
                ('review_time', models.TimeField(default=datetime.time(18, 0))),
                ('pause_until', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='method_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=25)),
                ('kind', models.CharField(choices=[('work', 'Travail'), ('buffer', 'Tampon')], default='work', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['weekday', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('color', models.CharField(choices=[('green', 'Vert'), ('orange', 'Orange'), ('red', 'Rouge')], max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daylog_per_day')],
            },
        ),
        migrations.CreateModel(
            name='SlotOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=25)),
                ('kind', models.CharField(choices=[('work', 'Travail'), ('buffer', 'Tampon')], default='work', max_length=8)),
                ('status', models.CharField(choices=[('planned', 'Prévu'), ('honored', 'Honoré'), ('missed', 'Raté'), ('excused', 'Excusé'), ('recovered', 'Rattrapé'), ('free', 'Libre')], default='planned', max_length=10)),
                ('excuse_reason', models.CharField(blank=True, choices=[('joker', 'Joker'), ('rouge', 'Journée rouge'), ('pause', 'Pause')], max_length=8)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('due_sent_at', models.DateTimeField(blank=True, null=True)),
                ('nudge_sent_at', models.DateTimeField(blank=True, null=True)),
                ('focus_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='focus.focussession')),
                ('recovers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_by', to='method.slotoccurrence')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='method.slot')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_occurrences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('slot', 'date'), name='unique_occurrence_per_slot_day')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('upcoming_sent_at', models.DateTimeField(blank=True, null=True)),
                ('due_sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('level_before', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level_after', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'constraints': [models.UniqueConstraint(fields=('user', 'week_start'), name='unique_review_per_week')],
            },
        ),
    ]
