# Generated by Django 6.0.6 on 2026-07-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdelivery',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
    ]
