# Generated by Django 6.0.6 on 2026-06-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='hidden_hours_end',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='hidden_hours_start',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
