# Generated by Django 6.0.6 on 2026-06-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usersettings_calendar_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='daily_review_evening',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='daily_review_morning',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
