# Generated by Django 6.0.6 on 2026-10-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_fcmdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
