# Generated by Django 6.0.6 on 2026-10-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usersettings_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='local_reminders',
            field=models.BooleanField(default=False),
        ),
    ]
