# Generated by Django 6.0.6 on 2026-06-13 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('relative', 'Relative'), ('absolute', 'Absolute')], default='relative', max_length=16)),
                ('minutes_before', models.IntegerField(blank=True, null=True)),
                ('trigger_at', models.DateTimeField(blank=True, null=True)),
                ('annoying', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.task')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
