# Generated by Django 6.0.6 on 2026-06-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_archived_at_attachment_taskversion_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
