# Generated by Django 6.0.6 on 2026-06-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_add_planned_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
