# Generated by Django 6.0.6 on 2026-06-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_reminder_dispatched_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
