# Generated by Django 6.0.6 on 2026-07-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_add_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='actor',
            field=models.CharField(default='user', max_length=64),
        ),
        migrations.AddField(
            model_name='task',
            name='claimed_by',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='task',
            name='last_actor',
            field=models.CharField(default='user', max_length=64),
        ),
    ]
