# Generated by Django 6.0.6 on 2026-10-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_activitylog_actor_task_claimed_by_task_last_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocker',
            field=models.CharField(blank=True, choices=[('boring', 'Ennuyeuse'), ('unclear', 'Floue'), ('too_big', 'Trop grosse'), ('unpleasant', 'Désagréable'), ('useless', 'Plus utile')], max_length=12),
        ),
        migrations.AddField(
            model_name='task',
            name='postpone_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='proposed',
            field=models.BooleanField(default=False),
        ),
    ]
