# Generated by Django 6.0.6 on 2026-07-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='planned_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
