# Generated by Django 6.0.6 on 2026-07-25 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tz', models.CharField(default='UTC', max_length=64)),
                ('mood', models.CharField(blank=True, max_length=300, verbose_name='ressenti général')),
                ('mood_noted_at', models.DateTimeField(blank=True, null=True)),
                ('mood_actor', models.CharField(default='user', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JournalMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('positif', 'Moment positif'), ('negatif', 'Moment négatif'), ('anecdote', 'Anecdote'), ('ressenti', 'Ressenti')], max_length=16)),
                ('text', models.TextField()),
                ('noted_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(default='user', max_length=64)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='journal.journalentry')),
            ],
            options={
                'ordering': ['noted_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_journal_day'),
        ),
    ]
